// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // __EFMigrationsHistory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class EfMigrationsHistoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<EfMigrationsHistory>
    {
        public EfMigrationsHistoryConfiguration()
            : this("dbo")
        {
        }

        public EfMigrationsHistoryConfiguration(string schema)
        {
            ToTable("__EFMigrationsHistory", schema);
            HasKey(x => x.MigrationId);

            Property(x => x.MigrationId).HasColumnName(@"MigrationId").HasColumnType("nvarchar").IsRequired().HasMaxLength(150).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ProductVersion).HasColumnName(@"ProductVersion").HasColumnType("nvarchar").IsRequired().HasMaxLength(32);
        }
    }

}
// </auto-generated>
