// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    public interface IMyDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<EfMigrationsHistory> EfMigrationsHistories { get; set; } // __EFMigrationsHistory
        System.Data.Entity.DbSet<Pedido> Pedidoes { get; set; } // Pedido
        System.Data.Entity.DbSet<PedidoItem> PedidoItems { get; set; } // PedidoItem
        System.Data.Entity.DbSet<Perfil> Perfils { get; set; } // Perfil
        System.Data.Entity.DbSet<PerfilAtributo> PerfilAtributoes { get; set; } // PerfilAtributo
        System.Data.Entity.DbSet<Produto> Produtoes { get; set; } // Produto
        System.Data.Entity.DbSet<Usuario> Usuarios { get; set; } // Usuario
        System.Data.Entity.DbSet<UsuarioAtributo> UsuarioAtributoes { get; set; } // UsuarioAtributo
        System.Data.Entity.DbSet<UsuarioProvedor> UsuarioProvedors { get; set; } // UsuarioProvedor
        System.Data.Entity.DbSet<UsuarioProvedorLogin> UsuarioProvedorLogins { get; set; } // UsuarioProvedorLogin

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
