// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    using System.Linq;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class MyDbContext : System.Data.Entity.DbContext, IMyDbContext
    {
        public System.Data.Entity.DbSet<EfMigrationsHistory> EfMigrationsHistories { get; set; } // __EFMigrationsHistory
        public System.Data.Entity.DbSet<Pedido> Pedidoes { get; set; } // Pedido
        public System.Data.Entity.DbSet<PedidoItem> PedidoItems { get; set; } // PedidoItem
        public System.Data.Entity.DbSet<Perfil> Perfils { get; set; } // Perfil
        public System.Data.Entity.DbSet<PerfilAtributo> PerfilAtributoes { get; set; } // PerfilAtributo
        public System.Data.Entity.DbSet<Produto> Produtoes { get; set; } // Produto
        public System.Data.Entity.DbSet<Usuario> Usuarios { get; set; } // Usuario
        public System.Data.Entity.DbSet<UsuarioAtributo> UsuarioAtributoes { get; set; } // UsuarioAtributo
        public System.Data.Entity.DbSet<UsuarioProvedor> UsuarioProvedors { get; set; } // UsuarioProvedor
        public System.Data.Entity.DbSet<UsuarioProvedorLogin> UsuarioProvedorLogins { get; set; } // UsuarioProvedorLogin

        static MyDbContext()
        {
            System.Data.Entity.Database.SetInitializer<MyDbContext>(null);
        }

        public MyDbContext()
            : base("Name=MyDbContext")
        {
        }

        public MyDbContext(string connectionString)
            : base(connectionString)
        {
        }

        public MyDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public MyDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public MyDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new EfMigrationsHistoryConfiguration());
            modelBuilder.Configurations.Add(new PedidoConfiguration());
            modelBuilder.Configurations.Add(new PedidoItemConfiguration());
            modelBuilder.Configurations.Add(new PerfilConfiguration());
            modelBuilder.Configurations.Add(new PerfilAtributoConfiguration());
            modelBuilder.Configurations.Add(new ProdutoConfiguration());
            modelBuilder.Configurations.Add(new UsuarioConfiguration());
            modelBuilder.Configurations.Add(new UsuarioAtributoConfiguration());
            modelBuilder.Configurations.Add(new UsuarioProvedorConfiguration());
            modelBuilder.Configurations.Add(new UsuarioProvedorLoginConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new EfMigrationsHistoryConfiguration(schema));
            modelBuilder.Configurations.Add(new PedidoConfiguration(schema));
            modelBuilder.Configurations.Add(new PedidoItemConfiguration(schema));
            modelBuilder.Configurations.Add(new PerfilConfiguration(schema));
            modelBuilder.Configurations.Add(new PerfilAtributoConfiguration(schema));
            modelBuilder.Configurations.Add(new ProdutoConfiguration(schema));
            modelBuilder.Configurations.Add(new UsuarioConfiguration(schema));
            modelBuilder.Configurations.Add(new UsuarioAtributoConfiguration(schema));
            modelBuilder.Configurations.Add(new UsuarioProvedorConfiguration(schema));
            modelBuilder.Configurations.Add(new UsuarioProvedorLoginConfiguration(schema));
            return modelBuilder;
        }
    }
}
// </auto-generated>
