// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // Pedido
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Pedido
    {
        public int Id { get; set; } // Id (Primary key)
        public System.DateTime DataPedido { get; set; } // DataPedido
        public string NumeroPedido { get; set; } // NumeroPedido
        public string UsuarioId { get; set; } // UsuarioId (length: 450)

        // Reverse navigation

        /// <summary>
        /// Child PedidoItems where [PedidoItem].[PedidoId] point to this entity (FK_PedidoItem_Pedido_PedidoId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PedidoItem> PedidoItems { get; set; } // PedidoItem.FK_PedidoItem_Pedido_PedidoId

        // Foreign keys

        /// <summary>
        /// Parent Usuario pointed by [Pedido].([UsuarioId]) (FK_Pedido_Usuario_UsuarioId)
        /// </summary>
        public virtual Usuario Usuario { get; set; } // FK_Pedido_Usuario_UsuarioId

        public Pedido()
        {
            PedidoItems = new System.Collections.Generic.List<PedidoItem>();
        }
    }

}
// </auto-generated>
