// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // PedidoItem
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class PedidoItemConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PedidoItem>
    {
        public PedidoItemConfiguration()
            : this("dbo")
        {
        }

        public PedidoItemConfiguration(string schema)
        {
            ToTable("PedidoItem", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ProdutoId).HasColumnName(@"ProdutoId").HasColumnType("int").IsOptional();
            Property(x => x.Quantidade).HasColumnName(@"Quantidade").HasColumnType("int").IsRequired();
            Property(x => x.PrecoUnitario).HasColumnName(@"PrecoUnitario").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.PedidoId).HasColumnName(@"PedidoId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Pedido).WithMany(b => b.PedidoItems).HasForeignKey(c => c.PedidoId).WillCascadeOnDelete(false); // FK_PedidoItem_Pedido_PedidoId
            HasOptional(a => a.Produto).WithMany(b => b.PedidoItems).HasForeignKey(c => c.ProdutoId).WillCascadeOnDelete(false); // FK_PedidoItem_Produto_ProdutoId
        }
    }

}
// </auto-generated>
