// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // Pedido
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class PedidoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Pedido>
    {
        public PedidoConfiguration()
            : this("dbo")
        {
        }

        public PedidoConfiguration(string schema)
        {
            ToTable("Pedido", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DataPedido).HasColumnName(@"DataPedido").HasColumnType("datetime2").IsRequired();
            Property(x => x.NumeroPedido).HasColumnName(@"NumeroPedido").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.UsuarioId).HasColumnName(@"UsuarioId").HasColumnType("nvarchar").IsOptional().HasMaxLength(450);

            // Foreign keys
            HasOptional(a => a.Usuario).WithMany(b => b.Pedidoes).HasForeignKey(c => c.UsuarioId).WillCascadeOnDelete(false); // FK_Pedido_Usuario_UsuarioId
        }
    }

}
// </auto-generated>
