// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // Perfil
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Perfil
    {
        public string Id { get; set; } // Id (Primary key) (length: 450)
        public string Nome { get; set; } // Nome (length: 256)
        public string NomeNormalizado { get; set; } // NomeNormalizado (length: 256)
        public string ChaveAlteracao { get; set; } // ChaveAlteracao

        // Reverse navigation

        /// <summary>
        /// Child PerfilAtributoes where [PerfilAtributo].[PerfilId] point to this entity (FK_PerfilAtributo_Perfil_PerfilId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PerfilAtributo> PerfilAtributoes { get; set; } // PerfilAtributo.FK_PerfilAtributo_Perfil_PerfilId
        /// <summary>
        /// Child Usuarios (Many-to-Many) mapped by table [UsuarioPerfil]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Usuario> Usuarios { get; set; } // Many to many mapping

        public Perfil()
        {
            PerfilAtributoes = new System.Collections.Generic.List<PerfilAtributo>();
            Usuarios = new System.Collections.Generic.List<Usuario>();
        }
    }

}
// </auto-generated>
