// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // PerfilAtributo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class PerfilAtributoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PerfilAtributo>
    {
        public PerfilAtributoConfiguration()
            : this("dbo")
        {
        }

        public PerfilAtributoConfiguration(string schema)
        {
            ToTable("PerfilAtributo", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PerfilId).HasColumnName(@"PerfilId").HasColumnType("nvarchar").IsRequired().HasMaxLength(450);
            Property(x => x.TipoAtributo).HasColumnName(@"TipoAtributo").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ValorAtributo).HasColumnName(@"ValorAtributo").HasColumnType("nvarchar(max)").IsOptional();

            // Foreign keys
            HasRequired(a => a.Perfil).WithMany(b => b.PerfilAtributoes).HasForeignKey(c => c.PerfilId); // FK_PerfilAtributo_Perfil_PerfilId
        }
    }

}
// </auto-generated>
