// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // PerfilAtributo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class PerfilAtributo
    {
        public int Id { get; set; } // Id (Primary key)
        public string PerfilId { get; set; } // PerfilId (length: 450)
        public string TipoAtributo { get; set; } // TipoAtributo
        public string ValorAtributo { get; set; } // ValorAtributo

        // Foreign keys

        /// <summary>
        /// Parent Perfil pointed by [PerfilAtributo].([PerfilId]) (FK_PerfilAtributo_Perfil_PerfilId)
        /// </summary>
        public virtual Perfil Perfil { get; set; } // FK_PerfilAtributo_Perfil_PerfilId
    }

}
// </auto-generated>
