// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // Produto
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Produto
    {
        public int Id { get; set; } // Id (Primary key)
        public string Categoria { get; set; } // Categoria
        public string Tamanho { get; set; } // Tamanho
        public decimal Preco { get; set; } // Preco
        public string Titulo { get; set; } // Titulo
        public string ArteDescricao { get; set; } // ArteDescricao
        public string ArteData { get; set; } // ArteData
        public string ArteCodigo { get; set; } // ArteCodigo
        public string Artista { get; set; } // Artista
        public System.DateTime ArtistaNascimento { get; set; } // ArtistaNascimento
        public System.DateTime ArtistaMorte { get; set; } // ArtistaMorte
        public string ArtistaNacionalidade { get; set; } // ArtistaNacionalidade

        // Reverse navigation

        /// <summary>
        /// Child PedidoItems where [PedidoItem].[ProdutoId] point to this entity (FK_PedidoItem_Produto_ProdutoId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PedidoItem> PedidoItems { get; set; } // PedidoItem.FK_PedidoItem_Produto_ProdutoId

        public Produto()
        {
            PedidoItems = new System.Collections.Generic.List<PedidoItem>();
        }
    }

}
// </auto-generated>
