// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // Produto
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ProdutoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Produto>
    {
        public ProdutoConfiguration()
            : this("dbo")
        {
        }

        public ProdutoConfiguration(string schema)
        {
            ToTable("Produto", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Categoria).HasColumnName(@"Categoria").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Tamanho).HasColumnName(@"Tamanho").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Preco).HasColumnName(@"Preco").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.Titulo).HasColumnName(@"Titulo").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ArteDescricao).HasColumnName(@"ArteDescricao").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ArteData).HasColumnName(@"ArteData").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ArteCodigo).HasColumnName(@"ArteCodigo").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Artista).HasColumnName(@"Artista").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ArtistaNascimento).HasColumnName(@"ArtistaNascimento").HasColumnType("datetime2").IsRequired();
            Property(x => x.ArtistaMorte).HasColumnName(@"ArtistaMorte").HasColumnType("datetime2").IsRequired();
            Property(x => x.ArtistaNacionalidade).HasColumnName(@"ArtistaNacionalidade").HasColumnType("nvarchar(max)").IsOptional();
        }
    }

}
// </auto-generated>
