// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // UsuarioProvedorLogin
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class UsuarioProvedorLoginConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UsuarioProvedorLogin>
    {
        public UsuarioProvedorLoginConfiguration()
            : this("dbo")
        {
        }

        public UsuarioProvedorLoginConfiguration(string schema)
        {
            ToTable("UsuarioProvedorLogin", schema);
            HasKey(x => new { x.LoginProvedor, x.ChaveProvedor });

            Property(x => x.LoginProvedor).HasColumnName(@"LoginProvedor").HasColumnType("nvarchar").IsRequired().HasMaxLength(450).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ChaveProvedor).HasColumnName(@"ChaveProvedor").HasColumnType("nvarchar").IsRequired().HasMaxLength(450).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.NomeProvedor).HasColumnName(@"NomeProvedor").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.UsuarioId).HasColumnName(@"UsuarioId").HasColumnType("nvarchar").IsRequired().HasMaxLength(450);

            // Foreign keys
            HasRequired(a => a.Usuario).WithMany(b => b.UsuarioProvedorLogins).HasForeignKey(c => c.UsuarioId); // FK_UsuarioProvedorLogin_Usuario_UsuarioId
        }
    }

}
// </auto-generated>
