// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // UsuarioAtributo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class UsuarioAtributoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UsuarioAtributo>
    {
        public UsuarioAtributoConfiguration()
            : this("dbo")
        {
        }

        public UsuarioAtributoConfiguration(string schema)
        {
            ToTable("UsuarioAtributo", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UsuarioId).HasColumnName(@"UsuarioId").HasColumnType("nvarchar").IsRequired().HasMaxLength(450);
            Property(x => x.TipoAtributo).HasColumnName(@"TipoAtributo").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ValorAtributo).HasColumnName(@"ValorAtributo").HasColumnType("nvarchar(max)").IsOptional();

            // Foreign keys
            HasRequired(a => a.Usuario).WithMany(b => b.UsuarioAtributoes).HasForeignKey(c => c.UsuarioId); // FK_UsuarioAtributo_Usuario_UsuarioId
        }
    }

}
// </auto-generated>
