// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // UsuarioProvedor
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class UsuarioProvedorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UsuarioProvedor>
    {
        public UsuarioProvedorConfiguration()
            : this("dbo")
        {
        }

        public UsuarioProvedorConfiguration(string schema)
        {
            ToTable("UsuarioProvedor", schema);
            HasKey(x => new { x.UsuarioId, x.LoginProvedor, x.Nome });

            Property(x => x.UsuarioId).HasColumnName(@"UsuarioId").HasColumnType("nvarchar").IsRequired().HasMaxLength(450).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.LoginProvedor).HasColumnName(@"LoginProvedor").HasColumnType("nvarchar").IsRequired().HasMaxLength(450).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Nome).HasColumnName(@"Nome").HasColumnType("nvarchar").IsRequired().HasMaxLength(450).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Valor).HasColumnName(@"Valor").HasColumnType("nvarchar(max)").IsOptional();

            // Foreign keys
            HasRequired(a => a.Usuario).WithMany(b => b.UsuarioProvedors).HasForeignKey(c => c.UsuarioId); // FK_UsuarioProvedor_Usuario_UsuarioId
        }
    }

}
// </auto-generated>
