// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ArquiteturaBase.Gerador
{

    // UsuarioProvedorLogin
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class UsuarioProvedorLogin
    {
        public string LoginProvedor { get; set; } // LoginProvedor (Primary key) (length: 450)
        public string ChaveProvedor { get; set; } // ChaveProvedor (Primary key) (length: 450)
        public string NomeProvedor { get; set; } // NomeProvedor
        public string UsuarioId { get; set; } // UsuarioId (length: 450)

        // Foreign keys

        /// <summary>
        /// Parent Usuario pointed by [UsuarioProvedorLogin].([UsuarioId]) (FK_UsuarioProvedorLogin_Usuario_UsuarioId)
        /// </summary>
        public virtual Usuario Usuario { get; set; } // FK_UsuarioProvedorLogin_Usuario_UsuarioId
    }

}
// </auto-generated>
